# Generated by Django 3.2.13 on 2022-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221116_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
